### ISSUE TITLE
Commands cannot be added to User Token based auth

### ISSUE THREAD

**Issue by Nivroc** [nitros12/calamity#26]
Sorry for a stupid question - haskell beginner here)
Is this the intended behaviour?
I cannot pinpoint anywhere in the control flow when this gets turned on/off. The received messages are the same that means same Context could be built from them.

**Comment by nitros12** [comment]
Userbots are against Discord's ToS so I have no motivation to support the
slight differences between user and bot accounts (sharding, etc).

**Comment by nitros12** [comment]
There's some code that has since been deleted that might work for using a
user token, but I have no idea if it works (and can't test it).

**Comment by Nivroc** [comment]
Thanks for quick reply, thought so.
