### ISSUE TITLE
No Guild Create events as guilds become available

### ISSUE THREAD

**Issue by Kaptch** [nitros12/calamity#27]
Upon start guilds that the bot is a part of will start out as unavailable, and stay so because no Guild Create event is received to update their status. I'll investigate further, but it appears that the problem happens somewhere before handleEvent.

**Comment by nitros12** [comment]
It's always worked for me. Are you using intents?

**Comment by Kaptch** [comment]
No, I'm using runBotIO without intents. It's rather odd because other events work absolutely fine.

**Comment by Kaptch** [comment]
Oh, I found the cause of the problem. I'll make a PR in a few minutes.

**Comment by Kaptch** [comment]
I had a custom activity type, which caused an error during parsing of the event.
