### ISSUE TITLE
Member fields

### ISSUE THREAD

**Issue by Kaptch** [nitros12/calamity#29]
It's rather a question than an issue. How does the Member datatype initialize a guild id field? Is it initialized somewhere inside the library? I'm trying to work on some voice chat solution, and VoiceStateUpdateData fails to be parsed from a JSON because its inner Member field fails to be parsed. I can use guild id from VoiceStateUpdateData itself, but I'm not sure if it is a good idea.

**Comment by nitros12** [comment]
The guild id is injected in the fromjson impl for Guild: https://github.com/nitros12/calamity/blob/master/src/Calamity/Types/Model/Guild/Guild.hs#L77

**Comment by Kaptch** [comment]
Oh, I see. Thank you! I'll use the same approach.
