### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by hgsipiere** [nitros12/calamity#30]
A tutorial, explaining step by step the DSL would be nice.

**Comment by nitros12** [comment]
Hi, I've added some more content to the command docs: https://hackage.haskell.org/package/calamity-0.1.20.1/docs/Calamity-Commands-Dsl.html

If there's some part you're confused by please let me know.

**Comment by hgsipiere** [comment]
Hi, so my understanding of Polysemy is that we want to run all our effects so we get rid of metrics with `runMetricsNoop`. When I do `runDiNoop` I seem to get an infinite loop, what am I doing wrong?
This is the project: https://github.com/hgsipiere/problem

Specifically this is the problematic line set:
`  void . P.runFinal . P.embedToFinal. D.runDiNoop . runCacheInMemory . runMetricsNoop . useConstantPrefix "!"
    $ runBotIO (BotToken token) $ do
    addCommands $ do
      helpCommand`

**Comment by nitros12** [comment]
Hm, I compiled that project and everything works fine.

**Comment by hgsipiere** [comment]
Hi sorry, it does work perfectly I was just confused. When I ran the calamity [example](https://github.com/nitros12/calamity-example/blob/master/app/Main.hs), there seems to be logging without a run Di. If I wanted that level of logging and nothing extra (which I realise now is more than noop), what would you recommend?

**Comment by nitros12** [comment]
ah, I've forgotten to update calamity-example.

The project that's up to date is calamity-bot, you can see an example of usage here:
https://github.com/nitros12/calamity-bot/blob/master/src/CalamityBot.hs#L43

If you want to control the log level, use the filter function from di-core:
 https://hackage.haskell.org/package/di-core-1.0.4/docs/Di-Core.html#v:filter

**Comment by hgsipiere** [comment]
Ahh thank you, that sorted my problem. The other thing that I'm confused about is the ban example (https://hackage.haskell.org/package/calamity-0.1.20.1/docs/Calamity-Commands-Dsl.html ), my alternative was
` void . invoke $ CreateGuildBan guild uid (CreateGuildBanData Nothing $ Just r)`. `reason` seems to conditionally implement the typeclass `Request` to give `invoke` from `Calamity.HTTP.Reason`; in this case it also doesn't complete the curried `CreateGuildBan` since it needs a `GuildBanData`. There is also another definition of `reason` as an AuditLogEntry constructor but that takes a `Maybe Text` which isn't a guild ban.

The other things that I was confused about were guilds since the Discord UI calls them servers, snowflakes and what bot tokens were. These were just sorted from consulting the Discord API documentation (this clarified what deleteMessageDays are for as another example).

Is there a discord or irc for questions? An issue feels kind of inappropriate.

**Comment by nitros12** [comment]
the 'ban' example is incorrect and is missing the ban data yeah, the `Calamity.HTTP.Reason.reason` function is used to add the `X-Audit-Log-Reason` http header to the request, the 'reason' field of `CreateGuildBanData` is the correct way to attach the reason info for bans.

I'll push an update correcting that example in a bit.

I've made a guild for this here: https://discord.gg/NGCThCY

**Comment by hgsipiere** [comment]
Thank you, that guild is helpful. I don't know if a tutorial will be
helpful as it more easily falls out of sync with the source than the
documentation.

At first I thought it might be helpful to explain what the examples
actually do line by line but this is more to maintain. I suppose a tutorial
could be paired with a CI that runs periodically to check it builds with
the latest calamity but this is a lot.

I'll close this issue tomorrow unless you have any thoughts.
