### ISSUE TITLE
no way to upgrade Snowflake Role to Role

### ISSUE THREAD

**Issue by elyatai** [nitros12/calamity#32]
there doesn't seem to be any way to go from a Snowflake Role to a Role; they're not Upgradeable and there's no GetGuildRole GuildRequest. my current workaround for now is [invoking GetGuildRoles and picking out the role by id](https://github.com/elyatai/clam/blob/32d1e39707b1a1c5e15d5c371202fdcc67625220/src/Clam/Commands/Roles.hs#L32-L38)

**Comment by nitros12** [comment]
Yup, I've added these in as of 22713b8, it'll be up on hackage under the version 0.1.24.0 when the CI finishes.

**Comment by elyatai** [comment]
gotcha, thank you!
