### ISSUE TITLE
No way to upgrade Snowflake VoiceChannel to VoiceChannel

### ISSUE THREAD

**Issue by Innf107** [nitros12/calamity#37]
It seens like it's currently impossible to upgrade Snowflake VoiceChannel to VoiceChannel. 
Sorry, if I just missed the intended solution.
My workaround so far was to create my own orphan instance
```haskell
instance Upgradeable VoiceChannel (Snowflake VoiceChannel) where
    upgrade s = upgrade (coerceSnowflake @_ @Channel s) <&> \case
            Just (GuildChannel' (GuildVoiceChannel vc)) -> Just vc
            _ -> Nothing
```

**Comment by nitros12** [comment]
Yeah the current way is probably to do that, adding Upgradeable instances for all the channel types would definitely be useful though
