### ISSUE TITLE
recently started getting ERROR Something went wrong with the http client

### ISSUE THREAD

**Issue by Miezhiko** [nitros12/calamity#69]
(InternalException (HandshakeFailed (Error_Protocol ("expecting server hello, got alert : [(AlertLevel_Fatal,DecodeError)]",True
,HandshakeFailure)))))

```
024-06-05T11:41:27.596422788Z /calamity /calamity route=https://discord.com/api/v10/gateway/bot DEBUG Internal error, retrying
024-06-05T11:41:27.596439133Z /calamity /calamity route=https://discord.com/api/v10/gateway/bot DEBUG unknown ratelimit
024-06-05T11:41:27.596451625Z /calamity /calamity route=https://discord.com/api/v10/gateway/bot DEBUG Request failed after 5 retries
```

wasn't able to guess what exactly broked and how, I did no changes, might be some discord API update

**Comment by simmsb** [comment]
This looks like an issue with HTTPS negotiation in the [tls library](https://github.com/haskell-tls/hs-tls/issues/470)
Perhaps this might be an issue with discord?
